name: "Issue Test"
on:
  issues:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          result-encoding: string
          script: console.log(context.issue)
