name: "Test"
on:
  push:

jobs:
  setup-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Commit and Push
        run: |
            git config --local user.name 'github-actions[bot]'
            git config --local user.mail 'github-actions[bot]@users.noreply.github.com'
            date > now.txt
            git add .
            git commit -m 'Update'
            git push
