name: "Test"
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: echo $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - run: pwd
      - run: echo $GITHUB_WORKSPACE

