name: "Test"
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo $MONTH
        env:
          MONTH: date +'%Y-%m'
      - run: echo "WITH_MONTH=$(date +'%Y-%m')" > $GITHUB_ENV
      - run: echo $MONTH
        with:
          MONTH: ${{ WITH_MONTH }}
