name: "Test"
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.action_repository }}
      - run: echo $GITHUB_ACTION_REPOSITORY
      - run: echo "/repos/${GITHUB_ACTION_REPOSITORY}/actions/runs"
      - run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            "/repos/${GITHUB_ACTION_REPOSITORY}/actions/runs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
