name: "Test"
on: push
jobs:
  test:
    strategy:
      matrix:
        php: [ 7.4, '8.1' ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - run: php${{ matrix.php }} -r 'echo ini_get("extension_dir");'
      - run: pecl config-show
      - run: pecl config-set ext_dir $(php${{ matrix.php }} -r 'echo ini_get("extension_dir");')
      - run: sudo pecl install runkit7-alpha
      - run: php${{ matrix.php }} -d extension=runkit7.so -r 'var_dump(get_loaded_extensions());'
