name: "Test"
on: push
jobs:
  test:
    strategy:
      matrix:
        php: [ 7.4, '8.1' ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - run: sudo pecl install runkit7-alpha
      - run: php${{ matrix.php }} -r 'var_dump(get_loaded_extensions());'
