name: "Test"
on: push
jobs:
  dotnet:
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2
      - run: which dotnet
      - run: ls -al ~/.dotnet
      - run: ls -al ~/.dotnet/sdk/*
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
      - run: which dotnet
      - run: ls -al ~/.dotnet
      - run: ls -al ~/.dotnet/sdk/*
      - run: dotnet --list-sdks
      - run: dotnet --version
