name: "Test"
on: push
jobs:
  test:
    strategy:
      matrix:
        php: [ 7.4, 8.0 ]
    runs-on: ubuntu-latest
    steps:
      - run: pecl install runkit7-alpha
      - run: php${{ matrix.php }} -r "echo runkit7_object_id([]) . PHP_EOL;"
