name: "Test"
on: push
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        postgres-verison: [ 9.6, 10 ]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:${{ matrix.postgres-verison }}
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Show PostgreSQL Version
        run: PGPASSWORD=password psql -U postgres -c "SELECT version();"
