name: "Test"
on: push
jobs:
  dotnet:
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2
      - name: Push
        run: |
          touch test.txt
          git commit -m 'From GitHub Action'
          git push origin master
