name: "Test"
on:
  push:

jobs:
  setup-database:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:oracle
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: database_name
          MYSQL_USER: database_user
          MYSQL_PASSWORD: database_password
          MYSQL_ROOT_HOST: '%'
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup MySQL
        run: |
          mysql -uroot -proot_password -hlocalhost -e 'create database test;'
