name: "Test"
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.action_repository }}/actions/runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
