name: "Test"
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Set repository name
        run:  echo "REPO_NAME=$(echo $GITHUB_REPOSITORY | grep -oP '(?<=/)(.+)')" >> $GITHUB_ENV
      - name: Set output file suffix
        if: ${{ matrix.os == 'Windows' }}
        run: echo "SUFFIX=.exe" >> $GITHUB_ENV
      - name: Build
        run: go build -o "${REPO_NAME}_${{ matrix.os }}_${{ matrix.arch }}${SUFFIX}"
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
      - run: ls -al
