name: "Test"
on: push
jobs:
  dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Test file
        run: echo > 'updated.' test.txt
      - name: Git Config
        run: |
          git config --global user.name aaa
          git config --global user.email "bbb@users.noreply.github.com"
      - name: Add
        run: git add .
      - name: Commit
        run: git commit -m 'From GitHub Action'
      - name: Push
        run: git push origin master

