name: "Test"
on: push
jobs:
  dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Test file
        run: touch test.txt
      - name: Commit
        run: git commit -m 'From GitHub Action'
      - name: Push
        run: git push origin master
