name: "Test"
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Commit and Push
        run: |
            NOW=$(date '+%Y%m%d%H%M%S' -d '9 hours')
            git config --global user.name 'github-actions[bot]'
            git config --global user.mail '41898282+github-actions[bot]@users.noreply.github.com'
            git switch -c "update-${NOW}"
            date > now.txt
            git add .
            git commit -m 'Update'
            hub pull-request --push --message  "update ${NOW}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
