name: "Test"
on:
  push:

jobs:
  test1:
    outputs:
      test1: ${{ steps.test.outputs.test1 }}
      test2: ${{ steps.test.outputs.test2 }}
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: test
        run: |
          echo "test1=${{ toJSON('[0, 1]') }}" >> $GITHUB_OUTPUT
          echo "test2=aaa" >> $GITHUB_OUTPUT

  test2:
    needs: test1
    if: ${{ needs.test1.outputs.test1 != '' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'test2'
  test3:
    needs: test1
    if: ${{ fromJSON(needs.test1.outputs.test1)[1] != 0 }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'test3'
  test4:
    needs: test1
    if: ${{ needs.test1.outputs.test2 != '' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'test4'
