name: "Test"
on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ macos-latest, macos-13, macos-12 ]
        dotnet-version: [ '3.1', '5.0', '6.0', '7.0', '8.0' ]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        id: setup-dotnet
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - run: dotnet --version
      - run: dotnet tool update --global JetBrains.ReSharper.GlobalTools --version 2023.3.4
